# Site settings
title: ODD 2017
subtitle: OpenData Day a Gioia del Colle
email: comunegioialive@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gioialab.github.io/oddgioiadelcolle/" # the base hostname & protocol for your site
author: Giuseppe Zileni
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/lagioiadigitale

# Build settings
markdown: kramdown

sass:
  style: compressed
